### ISSUE TITLE
Is really iOS 11 minimum version?

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS-Client-Swift#1]
- [ ] Bug
- [X] Question
- [ ] Suggetion
- [ ] Other

Hi when I try to use this with CocoaPods I got an error

> Specs satisfying the `ClusterWS-Client-Swift` dependency were found, but they required a higher minimum deployment target.

I see into source code and I found that the target version is for iOS 11, but my app must be compatible from 9.0 iOS version.
I really required iOS 11 version?

**Comment by davigr** [comment]
Hi @carmas123,

I guess minimum iOS version would be 10 due to swift 4.

Thanks

**Comment by romanbaitaliuk** [comment]
Hi @carmas123 ,

iOS 8.0, tvOS 9.0 and macOS 10.9 support available in 2.0.8 release.

Thanks
