### ISSUE TITLE
Support Swift 4.2

### ISSUE THREAD

**Issue by muhrifqii** [ClusterWS/ClusterWS-Client-Swift#4]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

### Details

Any plans for supporting Swift 4.2 and xcode 10?

**Comment by romanbaitaliuk** [comment]
Yes, it’s going to be available over weekend

Kind Regards,
Roman Baitaliuk

**Comment by romanbaitaliuk** [comment]
Hey @muhrifqii ,

New version 3.1.1 includes Swift 4.2 support. Let me know if any issues.

Thanks
