### ISSUE TITLE
Removing emitter event handler

### ISSUE THREAD

**Issue by muhrifqii** [ClusterWS/ClusterWS-Client-Swift#5]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

### Details

Is there any way to remove emitter event? Let's say I have a strong reference on particular event that needed to be removed. `CWSEmitter` doesn't have function for removing an event. Current workaround is to set some clossure to overwrite it using **on** function.

Addition:
I can't call `CWSEmitter.removeAllEvents` from `ClusterWS` instance

**Comment by muhrifqii** [comment]
should I make a PR for it? Or it's unnecessary

**Comment by muhrifqii** [comment]
@davigr ?

**Comment by romanbaitaliuk** [comment]
Hi @muhrifqii, sorry for delay. I do not have access to computer out of traveling. You can create PR, I’ll look at it. 

Thanks

**Comment by muhrifqii** [comment]
That's the PR #6 @davigr , it's been there for a while. Can you review it? I could only edit that using text editor, couldn't find the xcproject on the repo

**Comment by romanbaitaliuk** [comment]
Hi @muhrifqii, 

`3.1.3` is available in CocoaPods. Let me know if any issues.

Thanks
